on:
  schedule:
    - cron: '0 2 * * * '
  # See here: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  repository_dispatch:
    types: run
  push:
    paths:
    - 'samples/ClassroomLabs/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'samples/ClassroomLabs/**'
    - '.github/workflows/**'

name: AllTests

jobs:

  # You cannot use a matrix to define a shell: https://github.community/t5/GitHub-Actions/Using-matrix-to-specify-shell-is-it-possible/m-p/39869
  run-all-tests-core-win:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: '3.1.0'
        inlineScript: |
          Get-AzVM -ResourceGroupName "AzLabsLibrary"
    # - name: Execute steps
    #   shell: pwsh
    #   run: |
    #     Install-Module -Name Pester -Force -AllowClobber -RequiredVersion 4.10.1
    #     Install-Module Az -Force -AllowClobber
    #     Invoke-Pester ./samples/ClassroomLabs/Modules/Library/Tests/Fast* -EnableExit
