# It runs every day at 2am or when a push/pr is done on the library path or workflow path
# I couldn't get pester 5.0+ to work, fixed at a version that works
on:
  # See here: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  repository_dispatch:
    types: run
  push:
    paths:
    - 'samples/ClassroomLabs/**'
    - '.github/workflows/**'
    branches-ignore:
      - master
  pull_request:
    paths:
    - 'samples/ClassroomLabs/**'
    - '.github/workflows/**'
    branches-ignore:
      - master

name: LabServices-PowerShellLibrary-FastTests

jobs:

  # You cannot use a matrix to define a shell: https://github.community/t5/GitHub-Actions/Using-matrix-to-specify-shell-is-it-possible/m-p/39869
  run-all-tests-core-win:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Install-Module -Name Pester -Force -AllowClobber -RequiredVersion 4.10.1
          Invoke-Pester ./samples/ClassroomLabs/Modules/Library/Tests/Fast* -EnableExit

  run-all-tests-core-ubuntu:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          Install-Module -Name Pester -Force -AllowClobber -RequiredVersion 4.10.1
          Invoke-Pester ./samples/ClassroomLabs/Modules/Library/Tests/Fast* -EnableExit
