on: [push]

name: AzLabsCI

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Enable Azure context autosave
      shell: pwsh
      run: |
        Install-Module Az -Force
        Enable-AzContextAutosave

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Execute steps
      shell: pwsh
      run: |
        Install-Module Pester -Force
        Get-AzSubscription
        Invoke-Pester ./samples/ClassroomLabs/Modules/Library/Tests/Fast-Schedule.tests.ps1 -EnableExit